### ISSUE TITLE
GRU VS LSTM

### ISSUE THREAD

**Issue by ghazi-f** [ematvey/deep-text-classifier#17]
Hi @ematvey ,
First of all thanks a lot for your implementation !
This is actually more of a question than an Issue: If I'm not mistaken, your code seems to tell that you initially used GRU, then left it out for LSTM cells. Can I know the reasons ?

**Comment by ematvey** [comment]
LSTMs showed slightly higher final scores, I think. I also didn't see any significant difference in fw/bw speeds, convergence rates, or memory requirements (both cells are highly optimized in CuDNN). So I went with LSTMs.
Sorry, can't give any actual numbers, it was quite long time ago.
