### ISSUE TITLE
The Attention code

### ISSUE THREAD

**Issue by EthenZhang** [ematvey/deep-text-classifier#2]
Hi,ematvey. I have read the paper and I don't understand your code of the attention mechanism. According to you code ,how can I get the weight of each word in a sentence ?
thx.

**Comment by scylla** [comment]
The weighted projection seems to be incorrect.

**Comment by ematvey** [comment]
@scylla can you be more specific?

**Comment by scylla** [comment]
@ematvey in file model_components.py while calculating weighted_projection in function task_specific_attention i think we need to use inputs in place of input_projection, please correct me if i am wrong. 
thanks

**Comment by jknair** [comment]
@scylla the usage of input_projection is correct but the attention_weights are wrongly computed. 
@ematvey sent a pull request fixing that #5

**Comment by ematvey** [comment]
@jknair You are right, thanks for the PR! Amazing how such a serious bug only marginally degraded the performance.

Let's see how this affects performance. I'll retrain and report back the results.

**Comment by jknair** [comment]
Considering the number of classes were very less with the bug the system actually learnt across every dimension of the attention context vector. Apparently it learnt something 😁

**Comment by ematvey** [comment]
Strange, but accuracy only increased to 66.3% (from 65%), and I'm not sure if this is a result of attention fix and not due to longer training.

**Comment by bill-kalog** [comment]
@ematvey  inside the function `bidirectional_rnn()` at `model_components.py`, line 25 is
`outputs = tf.concat((fw_outputs, fw_outputs), 2)`. Shouldn't it be
`outputs = tf.concat((fw_outputs, bw_outputs), 2)` if you want to consider the backward output
for the attention too?
